#!/bin/bash

# Disable Unneeded Ubuntu FileSystems to Reduce Potential Attacking Surface
echo "======================================================================================"
echo "This Script Disables Unneeded Ubuntu FileSystems to Reduce Potential Attacking Surface"
echo "and Configures Directories Important Directories"
echo "======================================================================================"
echo ''

# Instruct modprobe to Force Inactive Modules to Always Fail Loading
# Create a File That Will be Used for Blacklisted Filesystems
touch /etc/modprobe.d/blacklisted_filesystems.conf
# Add Following Lines for the FileSystems Respectively
echo 'install cramfs /bin/true' >> /etc/modprobe.d/blacklisted_filesystems.conf
echo 'install freevxfs /bin/true' >> /etc/modprobe.d/blacklisted_filesystems.conf
echo 'install hfs /bin/true' >> /etc/modprobe.d/blacklisted_filesystems.conf
echo 'install hfsplus /bin/true' >> /etc/modprobe.d/blacklisted_filesystems.conf
echo 'install jffs2 /bin/true' >> /etc/modprobe.d/blacklisted_filesystems.conf
echo 'install udf /bin/true' >> /etc/modprobe.d/blacklisted_filesystems.conf

# Execute the Following Command to Unload the Module Respectively
rmmod cramfs
rmmod freevxfs
rmmod hfs
rmmod hfsplus
rmmod jffs2
rmmod udf

# Configure /tmp Directory
echo 'tmpfs /tmp  tmpfs defaults,rw,nosuid,nodev,noexec,relatime  0 0' >> /etc/fstab

# Configure /dev/shm Directory
echo 'tmpfs /dev/shm defaults,noexec,nodev,nosuid,size=2G 0 0' >> /etc/fstab

# Disable Automounting
if systemctl --now disable autofs; then
  echo 'Autofs Disabled...'
else
  echo 'Autofs was not installed.'
fi

# Disable USB Automounting
# Create a File That Will be Used to Disable USB Storage
if
touch /etc/modprobe.d/usb_storage.conf
# Add Following Line for USB Storage Disabling
echo 'install usb-storage /bin/true' >> /etc/modprobe.d/usb_storage.conf
# Execute the Following Command to Unload the Module
rmmod usb-storage; then
  echo 'USB Storage Disabled'
else
  echo 'USB Storage was Not Configured. No Action Necessary.'
fi
