#!/bin/bash

# Run the Following Command to Update chmod 444 to chmod 400 in /usr/sbin/grubmkconfig
sed -ri 's/chmod\s+[0-7][0-7][0-7]\s+\$\{grub_cfg\}\.new/chmod 400 ${grub_cfg}.new/' /usr/sbin/grub-mkconfig

# Run the Following Command to Remove Check on Password not Being set to Before Running chmod Command
 sed -ri 's/ && ! grep "\^password" \$\{grub_cfg\}.new >\/dev\/null//' /usr/sbin/grub-mkconfig
 
 # Ensure Bootloader Password is set
 
