#!/bin/bash

# Run the Following Command to Update chmod 444 to chmod 400 in /usr/sbin/grubmkconfig
echo "It might take some time. Please be patient..."
sed -ri 's/chmod\s+[0-7][0-7][0-7]\s+\$\{grub_cfg\}\.new/chmod 400 ${grub_cfg}.new/' /usr/sbin/grub-mkconfig

# Run the Following Command to Remove Check on Password not Being set to Before Running chmod Command
 sed -ri 's/ && ! grep "\^password" \$\{grub_cfg\}.new >\/dev\/null//' /usr/sbin/grub-mkconfig
 
# Ensure Bootloader Password is set
echo 'This Script Will Create Credentials for BootLoader.'
echo 'Please Provide and Write Down a Password That Will be Used for this Purpose.'
# Files passfile and unfile are Mandatory Because They Contain the Credentials.
cat passfile | grub2-mkpasswd-pbkdf2 | awk '/grub.pbkdf/{print$NF}'
echo 'The Script Will Use Username: bootloader1'
# You Can Use a Different Username Before Running the Script
echo 'The System Will Need to Reboot After Completion of Procedure'

